<?php

declare(strict_types=1);

namespace WebVision\DeeplWrite\Tests\Functional\Service;

use PHPUnit\Framework\Attributes\Test;
use WebVision\DeeplWrite\Service\DeeplService;
use WebVision\DeeplWrite\Tests\Functional\Helper\AbstractDeepLTestCase;

final class DeeplServiceTest extends AbstractDeepLTestCase
{
    protected array $testExtensionsToLoad = [
        'web-vision/deepl-write',
    ];

    protected array $configurationToUseInTestInstance = [
        'EXTENSIONS' => [
            'deepl_write' => [
                'apiKey' => 'mock_server',
            ],
        ],
    ];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[Test]
    public function basicTest(): void
    {
        /** @var DeeplService $service */
        $service = $this->get(DeeplService::class);
        $rephrase = $service->rephraseText(
            'teste mich einfach',
            'DE'
        );
    }
}
