name: tests core 12

on:
  workflow_dispatch:

jobs:
  dummy:
    name: "dummy v12 (disabled on main) to allow creation of badges for other branches"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
